language: node_js

sudo: false

node_js:
- 0.10

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11


install:
 - npm install

before_script:
 - if [[ ${COVERAGE:-false} != false ]]; then npm run coverage; fi;

script:
 - npm test